"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Download, Package } from "lucide-react"
import JSZip from "jszip"

interface ExportProject {
  name: string
  description: string
  code: string
  language: string
  framework: string
  dependencies: string[]
}

export function ProjectExporter() {
  const [project, setProject] = useState<ExportProject>({
    name: "Lady Violet's Creation",
    description: "A cyberpunk-themed application generated by Lady Violet",
    code: "",
    language: "javascript",
    framework: "react",
    dependencies: ["react", "react-dom", "tailwindcss"],
  })
  const [isExporting, setIsExporting] = useState(false)
  const [exportType, setExportType] = useState("pwa")

  const generatePackageJson = () => {
    return JSON.stringify(
      {
        name: project.name.toLowerCase().replace(/\s+/g, "-"),
        version: "1.0.0",
        description: project.description,
        main: "index.js",
        scripts: {
          start: "react-scripts start",
          build: "react-scripts build",
          test: "react-scripts test",
          eject: "react-scripts eject",
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1",
          tailwindcss: "^3.3.0",
          ...project.dependencies.reduce((acc, dep) => ({ ...acc, [dep]: "latest" }), {}),
        },
        browserslist: {
          production: [">0.2%", "not dead", "not op_mini all"],
          development: ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"],
        },
      },
      null,
      2,
    )
  }

  const generateManifest = () => {
    return JSON.stringify(
      {
        name: project.name,
        short_name: project.name.split(" ")[0],
        description: project.description,
        start_url: "/",
        display: "standalone",
        background_color: "#0a0a0a",
        theme_color: "#00ffff",
        orientation: "portrait-primary",
        icons: [
          {
            src: "/images/lady-violet-avatar.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "maskable",
          },
          {
            src: "/images/lady-violet-avatar.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
          },
        ],
        categories: ["productivity", "developer", "utilities"],
      },
      null,
      2,
    )
  }

  const generateElectronConfig = () => {
    return JSON.stringify(
      {
        name: project.name,
        version: "1.0.0",
        description: project.description,
        main: "public/electron.js",
        homepage: "./",
        scripts: {
          electron: "electron .",
          "electron-dev": "ELECTRON_IS_DEV=true electron .",
          dist: "electron-builder",
          pack: "electron-builder --dir",
        },
        build: {
          appId: `com.ladyviolet.${project.name.toLowerCase().replace(/\s+/g, "")}`,
          productName: project.name,
          directories: {
            output: "dist",
          },
          files: ["build/**/*", "node_modules/**/*", "public/electron.js"],
          mac: {
            category: "public.app-category.developer-tools",
          },
          win: {
            target: "nsis",
          },
          linux: {
            target: "AppImage",
          },
        },
        devDependencies: {
          electron: "^22.0.0",
          "electron-builder": "^23.6.0",
        },
      },
      null,
      2,
    )
  }

  const generateCapacitorConfig = () => {
    return JSON.stringify(
      {
        appId: `com.ladyviolet.${project.name.toLowerCase().replace(/\s+/g, "")}`,
        appName: project.name,
        webDir: "build",
        bundledWebRuntime: false,
        plugins: {
          SplashScreen: {
            launchShowDuration: 2000,
            backgroundColor: "#0a0a0a",
            showSpinner: true,
            spinnerColor: "#00ffff",
          },
        },
        server: {
          androidScheme: "https",
        },
      },
      null,
      2,
    )
  }

  const exportProject = async () => {
    setIsExporting(true)

    // Simulate export process
    await new Promise((resolve) => setTimeout(resolve, 2000))

    const files: { [key: string]: string } = {}

    // Base files
    files["package.json"] = generatePackageJson()
    files["README.md"] =
      `# ${project.name}\n\n${project.description}\n\nGenerated by Lady Violet's Cyberpunk Terminal\n\n## Installation\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\``

    // Add project-specific files based on export type
    switch (exportType) {
      case "pwa":
        files["public/manifest.json"] = generateManifest()
        files["public/sw.js"] = `
const CACHE_NAME = '${project.name.toLowerCase().replace(/\s+/g, "-")}-v1';
const urlsToCache = ['/'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(urlsToCache))
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request)
      .then((response) => response || fetch(event.request))
  );
});`
        break
      case "electron":
        files["package.json"] = generateElectronConfig()
        files["public/electron.js"] = `
const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false
    },
    icon: path.join(__dirname, 'images/lady-violet-avatar.png')
  });

  mainWindow.loadFile('build/index.html');
}

app.whenReady().then(createWindow);`
        break
      case "capacitor":
        files["capacitor.config.json"] = generateCapacitorConfig()
        break
    }

    // Create and download zip file
    const zip = new JSZip()
    Object.entries(files).forEach(([filename, content]) => {
      zip.file(filename, content)
    })

    const blob = await zip.generateAsync({ type: "blob" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${project.name.toLowerCase().replace(/\s+/g, "-")}-${exportType}.zip`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    setIsExporting(false)
  }

  return (
    <Card className="terminal-border bg-card/90 backdrop-blur-sm">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-primary">
          <Package className="w-5 h-5" />
          Project Exporter
          <Badge variant="outline" className="neon-glow">
            Multi-Platform
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <Tabs value={exportType} onValueChange={setExportType} className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="pwa">📱 PWA</TabsTrigger>
            <TabsTrigger value="electron">💻 Desktop</TabsTrigger>
            <TabsTrigger value="capacitor">🤖 Mobile</TabsTrigger>
          </TabsList>

          <TabsContent value="pwa" className="space-y-4">
            <div className="space-y-4">
              <div>
                <Label htmlFor="pwa-name">App Name</Label>
                <Input
                  id="pwa-name"
                  value={project.name}
                  onChange={(e) => setProject((prev) => ({ ...prev, name: e.target.value }))}
                />
              </div>
              <div>
                <Label htmlFor="pwa-desc">Description</Label>
                <Input
                  id="pwa-desc"
                  value={project.description}
                  onChange={(e) => setProject((prev) => ({ ...prev, description: e.target.value }))}
                />
              </div>
            </div>
            <div className="text-xs text-muted-foreground space-y-1">
              <div>✓ Service Worker for offline functionality</div>
              <div>✓ Web App Manifest for installation</div>
              <div>✓ Responsive design for all devices</div>
              <div>✓ Push notification support</div>
            </div>
          </TabsContent>

          <TabsContent value="electron" className="space-y-4">
            <div className="space-y-4">
              <div>
                <Label>Desktop Application Configuration</Label>
                <p className="text-sm text-muted-foreground mb-3">Create a cross-platform desktop app with Electron</p>
              </div>
              <div className="text-xs text-muted-foreground space-y-1">
                <div>✓ Windows, macOS, Linux support</div>
                <div>✓ Native system integration</div>
                <div>✓ Auto-updater support</div>
                <div>✓ System tray integration</div>
                <div>✓ File system access</div>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="capacitor" className="space-y-4">
            <div className="space-y-4">
              <div>
                <Label>Mobile Application Configuration</Label>
                <p className="text-sm text-muted-foreground mb-3">Build native iOS and Android apps with Capacitor</p>
              </div>
              <div className="text-xs text-muted-foreground space-y-1">
                <div>✓ Native iOS and Android apps</div>
                <div>✓ Access to device APIs</div>
                <div>✓ App store distribution ready</div>
                <div>✓ Push notifications</div>
                <div>✓ Camera and file access</div>
              </div>
            </div>
          </TabsContent>
        </Tabs>

        <div className="mt-6 space-y-4">
          <div>
            <Label htmlFor="project-code">Project Code</Label>
            <Textarea
              id="project-code"
              placeholder="Paste your generated code here..."
              value={project.code}
              onChange={(e) => setProject((prev) => ({ ...prev, code: e.target.value }))}
              className="min-h-[150px] font-mono text-sm"
            />
          </div>

          <Button onClick={exportProject} disabled={isExporting || !project.code.trim()} className="w-full neon-glow">
            {isExporting ? (
              <>🔄 Exporting {exportType.toUpperCase()}...</>
            ) : (
              <>
                <Download className="w-4 h-4 mr-2" />
                Export {exportType.toUpperCase()} Project
              </>
            )}
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
